apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-hello-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-hello-app
    spec:
      containers:
      - name: my-hello-app
        image: sonaereg.azurecr.io/my-hello-app:v1
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: my-hello-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-hello-app